=== David-Roses/David-Roses/xml/agenda.dtd
<!ELEMENT ejemplo-agenda (agenda, persona, personaid, nombre, tlf)>
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, tlf)>
<!ATTLIST personaid ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>

=== David-Roses/David-Roses/xml/ejemplo10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ejemplo-agenda SYSTEM "agenda.dtd">
<persona>
    <nombre></nombre>
    <tlf>951345679</tlf>
</persona>
<persona>
    <persona id="eva">
    <nombre>Eva Risto</nombre>
    <tlf>955837659</tlf>
    <tw>@Evaristo</tw>
</persona>
